### ISSUE TITLE
Convert proj files and update to new makefiles

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/UltraEncode#1]
Mediapede UltraEncode is a commercial software application brought to BeOS from the makers of UltraDV.
It would be a shame to lose these types of software for Haiku.
![ultraencode](https://user-images.githubusercontent.com/13264393/34403574-41deb42c-eb66-11e7-98a3-eeb68157c58b.gif)

**Comment by diversys** [comment]
And this is how it looks now:

<img src="https://user-images.githubusercontent.com/1316513/37158366-4922d90c-22fc-11e8-8633-6af4ecff1b46.png" width="75%">
